### ISSUE TITLE
Unavailable when charging

### ISSUE THREAD

**Issue by geoffro10** [mbillow/ha-chargepoint#14]
This just started showing for me but when I'm plugged in and charging, all my entities switch to unavailable. As soon as the charging is stopped, they all come back.

**Comment by geoffro10** [comment]
Of course as soon as I post something here, now it seems to be working. Was really weird. Did that for 3 straight days. I'll come back and close it out if it works the next few days.

**Comment by geoffro10** [comment]
Working fine now.

**Comment by crkochan** [comment]
I wonder if this might be due to the type of charging station you were using.

I've noticed that the integration entities regularly go unavailable when I'm using a CP station that is not public. These particular stations are located on the campuses of my company, and are free for employee use.

Today I noticed that the integration is throwing an exception trying to get data on the charging sessions in progress whilst plugged into one of these stations.

I wonder if that might have been happening here.

**Comment by geoffro10** [comment]
I don't think it's related because the first time was at my home on a Home Flex and the second was a public charger.

**Comment by crkochan** [comment]
The code in the underlying python module uses a suboptimal (in my opinion) method for getting the current charging status. It's rigidly coded, so if the status payload differs at all from how the developer wrote the code, it breaks, with the effect of all entities in HA going unavailable.

This could happen with public chargers, it could also happen with a Home Flex where the station hasn't been configured with utility information.

I opened [a PR](https://github.com/mbillow/python-chargepoint/pull/3) against the module with fixes.

**Comment by geoffro10** [comment]
That's interesting! I wish I knew more about coding so I could help. But FYI, my utility info is in my Home Flex.

**Comment by mbillow** [comment]
> The code in the underlying python module uses a suboptimal (in my opinion) method for getting the current charging status. It's rigidly coded…

I spend a lot of my time writing in strongly typed languages, so I tend to err in that direction even when using Python. I commented on the PR, there is definitely a middle ground. 

Happy to spend the time making this work in as many ways as possible. I will note that the HA module itself does some logical check to make sure the charging status it is returning belongs to the home charging device registered. I did that to keep this plugin simple and keep it true to the “Home” in Home Assistant. If you do want to track all your CP charging sessions, I’m not vehemently against a little extra logic to handle that as well.

**Comment by crkochan** [comment]
I think it's valid to limit the integration to tracking home sessions only. 

The contributions against the underlying library is just to keep the integration from emitting errors in the HA logs and having the integration flagged in the UI as having issues or needing to be re-setup when it's receiving session data from other than the home charger.

**Comment by mbillow** [comment]
@Wireless2455 Can you grab the relevant logs and paste them here?
