### ISSUE TITLE
state class log errors for 'measurement' and 'total_increasing'

### ISSUE THREAD

**Issue by rgb2017** [mbillow/ha-chargepoint#21]
WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.name_account_balance (<class 'custom_components.chargepoint.sensor.ChargePointSensorEntity'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.cph50_charge_cost (<class 'custom_components.chargepoint.sensor.ChargePointChargerSensorEntity'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by mbillow** [comment]
Thanks for reporting this. I'll get a patch out ASAP. 😄

**Comment by mbillow** [comment]
I fixed this and #20 in `v0.4.0`. Thanks again for bringing these warning up!
