### ISSUE TITLE
International login fails

### ISSUE THREAD

**Issue by unsoluble** [mbillow/ha-chargepoint#3]
Any chance the login service is US-only? I get `invalid credentials` here logging into the HCAS integration in Canada (which on the web takes me to `ca.chargepoint.com`).

**Comment by mbillow** [comment]
Interesting. Yes, I have only ever tested it with my US ChargePoint account. Let me make a Canadian account and see if I can get the right URLs.

**Comment by mbillow** [comment]
So it looks like the app makes a call to `https://discovery.chargepoint.com/discovery/v3/globalconfig` with the username that is trying to log in and that endpoint returns a map of region-specific services for us to talk to. Working on a new version of [mbillow/python-chargepoint](https://github.com/mbillow/python-chargepoint) that handles this discovery correctly and then I will pull it into the HA add-on.

**Comment by unsoluble** [comment]
Cool, thanks for investigating! Will be neat to be able to use this integration. :)

**Comment by mbillow** [comment]
I just published v0.2.0. Let me know how it goes!

**Comment by mbillow** [comment]
Closing the loop for @davcho80 as well, you should be good to upgrade and try again. 😄

**Comment by davcho80** [comment]
@mbillow ooh yes everything is good

**Comment by unsoluble** [comment]
Nailed it — logged in and running now. Thanks! :)

**Comment by mbillow** [comment]
Awesome, glad it works for y’all!
