### ISSUE TITLE
Not working in 2023.09.03

### ISSUE THREAD

**Issue by sorendayton** [mbillow/ha-chargepoint#32]
Hello,

The integration stopped working last month (I still had 2023.8 something installed). I upgraded HA and deleted and reinstalled the integration, and it still doesn't work. It hangs when I give my login credentials and never exits.

I know that ChargePoint changed some things on the website (making pulling data more annoying). I don't know if those are related.

**Comment by sorendayton** [comment]
update.chargepoint_update is:



update.chargepoint_updateChargePoint update | off | auto_update: false installed_version: v0.6.0 in_progress: false latest_version: v0.6.0 release_summary: null release_url: https://github.com/mbillow/ha-chargepoint/releases/v0.6.0 skipped_version: null title: null entity_picture: https://brands.home-assistant.io/_/chargepoint/icon.png friendly_name: ChargePoint update supported_features: 21
-- | -- | --


[update.chargepoint_update]()
ChargePoint update
off	auto_update: false
installed_version: v0.6.0
in_progress: false
latest_version: v0.6.0
release_summary: null
release_url: https://github.com/mbillow/ha-chargepoint/releases/v0.6.0
skipped_version: null
title: null
entity_picture: https://brands.home-assistant.io/_/chargepoint/icon.png
friendly_name: ChargePoint update
supported_features: 21

**Comment by mbillow** [comment]
Are there any useful log messages? 

There is another recent issue where the user tracked their problem down to potential changes in the regional endpoints. Do you live outside of the US?

**Comment by sorendayton** [comment]
I live in the US.

I have had debug logging on for a couple of days.   Nothing shows up


[image: Screenshot 2023-10-06 at 2.33.08 PM.png]

As I said, when I enter credentials, it just goes around and around and
around nothing happens.


[image: Screenshot 2023-10-06 at 2.30.15 PM.png]

I have the latest version installed

[image: Screenshot 2023-10-06 at 2.35.22 PM.png]

And I confirmed it's there by SSHing into my Raspberry PI and looking at
the filesystem.
