### ISSUE TITLE
Feature Request: Control Charge Current Limit

### ISSUE THREAD

**Issue by keith29394** [mbillow/ha-chargepoint#35]
The ChargePoint app lets you set Charge Current Limit.  It would be amazing to control this via HA to dynamically adjust the charging power level based on solar production.

**Comment by mbillow** [comment]
Agreed! Is this just a feature request or is this something you’d be interested in adding?

**Comment by keith29394** [comment]
Just a feature request.   I would love to add it myself, but unfortunately I don't have enough experience with coding in Python or HA to accomplish this myself without a steep learning curve (perhaps one day).  

As an experiment I did try changing the Charge Current Limit via the app during a charge session and it did dynamically change.  Hopefully the API allows it to be set via HA.  

BTW, thank you for creating this integration!  It has been super useful for dynamically controlling charging based on my PV excess power level.

**Comment by mbillow** [comment]
Added in #38 and released in `v0.7.0`. Closing this out.

**Comment by gigawatts** [comment]
@mbillow I can open a new issue if preferred, but what happened to this feature? "This entity is no longer being provided by the chargepoint integration."

The app still offers this setting.
