### ISSUE TITLE
All data is 'unavailable'

### ISSUE THREAD

**Issue by sxdjt** [mbillow/ha-chargepoint#42]
Just wondering if anybody else is seeing this problem or if it is just me.

All of the HA entities for the Chargepoint are reporting 'unavailable'.  Can't see any issues or logbook entries - it was working fine until a couple of days ago.

**Comment by sxdjt** [comment]
I am seeing occasional/intermittent data coming in...  is Chargepoint having a problem?

<img width="580" alt="Screenshot 2024-03-20 at 12 50 43" src="https://github.com/mbillow/ha-chargepoint/assets/53812540/2f0b26d8-bc46-47f8-b254-cc474a178027">

**Comment by SeanPM5** [comment]
It's not a problem with the integration, just ChargePoint network being down for the last day or so. Their app and public chargers aren't working either at the moment. See [here](https://twitter.com/ChargePointnet/status/1770254506686833004) and [here](https://twitter.com/ChargePointnet/status/1770474449789387069).

**Comment by sxdjt** [comment]
Thanks for the info @SeanPM5.  Glad it's not just me (this time).
