### ISSUE TITLE
Just one entity is shown

### ISSUE THREAD

**Issue by CSH12** [mbillow/ha-chargepoint#49]
Hi
I'm newly using the chargepoint integration and i'm a little wondering if it is just showing the account balance in case I haven't connected my home chargers, too.

So is it "normal" that it is just showing the account balance? 

(HA Version 2024.10.3; Chargepoint Version 0.8.0)

Thanks in advance.
Chris

**Comment by mbillow** [comment]
If the integration doesn’t detect any home chargers, it will only show you your balance, yes.

You will need to reload the integration or restart Home Assistant after registering a home charger in order for it to add the device and entities.

**Comment by nadler1ny** [comment]
Thank you for your response. That did it.  Regards,
Noel
